#+TITLE: CheckLT: Taint Checking for Mere Mortals
#+AUTHOR: John L. Singleton
#+OPTIONS: toc:nil
#+OPTIONS: num:nil

#+BEGIN_HTML
---
layout: default
permalink: index.html
release: 06042013
---
#+END_HTML


#+TOC: headlines 2


* What is CheckLT?

CheckLT is a program verification tool for Java which can help you use taint tracking to find defects in your software. CheckLT provides an easy to install verification toolset, a simple, non-invasive syntax for annotating programs, and a dynamically configurable security lattice. 

CheckLT was born out of a research project at the University of Central Florida where we are researching creating tools for secure information flow analysis for Android applications. CheckLT does not implement full information flow security, but instead aims at being a lightweight security analysis toolkit for Java. 

Though CheckLT relies on Checker Framework for its base functionality (in fact, it is a plugin for the checker framework) CheckLT is being distributed independently of Checker Framework as a part of an experiment by this author to make formal verification tools more easily accessible outside of the research community. You can think of it as a "Click, Run, Verify!" approach to formal methods software!

* Install
Before you install CheckLT, make sure you have a recent Java 7 (1.7) installed. You can use either the Oracle JDK or OpenJDK.

#+BEGIN_HTML
<div align="center">
<button type="button" href="#" class="btn btn-success btn-large" onclick="location.href='/releases/checklt-{{page.release}}.zip';"><i class="icon-white icon-arrow-down"></i> Download CheckLT</button>
</div>
#+END_HTML

To install, download the archive, and run the included jar file by double clicking on it. If for some reason your system does not suport running executable jar files by double clicking, you can install it from a command prompt by running:

#+BEGIN_SRC sh

# java -jar checklt-installer.jar

#+END_SRC 

Windows Users: To use CheckLT from the command line, please add the path you installed CheckLT in to your =PATH=. 

After you install CheckLT you can run it from the command prompt by running:

#+BEGIN_SRC sh

# checklt MyProgram.java

#+END_SRC 

Note that checklt supports all the commands available to a traditional Java compiler. To get a complete list of options, you can run the following command:

#+BEGIN_SRC sh

# checklt -help

#+END_SRC 


* Building CheckLT

To build CheckLT, you will need to have the build tool Gradle (version 1.4 or higher) and [[http://izpack.org/][IzPack]] installed (version 4 or higher). CheckLT's build scripts assume that the IzPack install directory is on your path. To build, simply use one of the gradle targets or simply:

#+BEGIN_SRC sh

# gradle

#+END_SRC

To build the entire distribution. All required dependencies will be fetched at build time. Note that you will need some recent Java 7 compiler (OpenJDK or Oracle) to compile CheckLT. 


* Setting Up for Development

CheckLT is currently primarily developed on Emacs using eclim. If you wish to use Eclipse (or eclim) for hacking on CheckLT, there is a special Gradle target for generating a Eclipse workspace for the CheckLT plugin. 

To do this, execute the following commands from the base of the source distribution:

#+BEGIN_SRC sh

# cd checker-lattice-tainting-plugin
# gradle -q eclipse

#+END_SRC

The directory =checker-lattice-tainting-plugin= will now be an Eclipse project directory which may be imported. 

Note that you must make a minor modification to the generated .classpath file.

In your .classpath file, make sure the following line is LAST.


#+BEGIN_SRC xml

 <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>

#+END_SRC

* Poor Man's Information Flow in Two Steps

To configure CheckLT for your application you must do two things. First, you must configure security rules for your particular application. In this process you will configure a /security lattice/, as we shall see in the next section. Once your security lattice is set up you can then annotate your program to reflect your concerns. The next two sections cover this process in detail.

** Configuring The Lattice

The first thing you must do is configure a security lattice for use with CheckLT. This file should be called =security.xml=, and it should be in the root directory from which you execute CheckLT. Note that CheckLT can (and will) check your proposed lattice for soundness before executing. As of the current version, CheckLT checks to make sure that no insecure flows are specified (via graph cycle checking) and that all specified trusts are reachable and properly declared. 

The following example represents a slightly more complicated lattice than you will need for most projects. It is presented simply to showcase some of the flexibility of CheckLT.


#+BEGIN_SRC xml

<linear-lattice>

    <!-- all levels must first be declared -->
    <levels>
        <level>Private</level>
        <level>UserTrusts</level>
        <level>User</level>
        <level>Public</level>
    </levels>


    <level-specs>

        <!-- level spec for Public -->
        <level-spec>
            <name>Public</name>

            <trusts>
                <level>Private</level>
                <level>UserTrusts</level>
                <level>User</level>
            </trusts>
        </level-spec>

        <!-- level spec for User -->
        <level-spec>
            <name>User</name>

            <trusts>
                <level>UserTrusts</level>

            </trusts>
        </level-spec>


        <!-- level spec for UserTrusts -->
        <level-spec>
            <name>UserTrusts</name>

            <trusts>
                <level>Private</level>

            </trusts>
        </level-spec>


        <!-- level spec for UserTrusts -->
        <level-spec>
            <name>Private</name>

            <trusts>
                <!-- trusts no one (other than self) -->
            </trusts>
        </level-spec>

    </level-specs>

</linear-lattice>

#+END_SRC

The labels in Listing X.X are explained as follows:

1. Public (⊥): Any information that may freely move through the application and conversely, the least trusted information level.
2. User: Information that is private and should only be known to the user.
3. UserTrusts: Information that is private, but may be shared with special endpoints that the user highly trusts. Endpoints may be specific instance variables, methods, or entire classes.
4. Private (⊤): The highest level of privacy. Information may not even be known to the user. An example of such a piece of information could be an internal result used for the verification of a serial number.

While more complex lattice structures are possible to represent in CheckLT, as of the current release, CheckLT recognizes a linear lattice at the moment. 

Graphically represented, the lattice described above looks like Figure X.X. As you can see, the reason we call this a linear lattice is that the structure is strongly linear; that is, information may travel upwards in the lattice, but not back down (without declassification).

** Label Syntax

Labels in CheckLT are specified using Java Annotations. The BNF syntax is given in Listing X.X.

#+BEGIN_SRC html

<level> ::= ‘"’ <string> ‘"’

<level-spec> ::= <level>

<security-annotation> ::= ‘@Level(’ <level-spec> ‘)’ 

#+END_SRC

** Declassification 

Declassification is essentially a controlled release of information. Depending on your application of CheckLT, you may or may not want explicit declassification. For example, if you are using CheckLT to do taint tracking against within SQL queries, you might want to specify that /no/ declassification may be performed. However, in the same scenario you might have some routine that "untaints" a tainted query. In such a case you will need declassification. 

Below is an example of explicit declassification. 


#+BEGIN_SRC java


TODO




#+END_SRC


* Example: Keeping SQL Queries Clean

TODO

* What's With the Name?

CheckLT is a plugin for the Checker Framework that checks for taint using a lattice. The "LT" in  CheckLT is for "Lattice Tainting." It is pronounced to rhyme with "Chicklet."

* Acknowledgements and Thanks

CheckLT is a direct byproduct of my work with Gary Leavens at the University of Central Florida and David Naumann the Stevens Insitute of Technology, to whom I am deeply grateful. Without their constant guidance (and correction!) and encouragement CheckLT wouldn't have been possible!


| test | test | test | test | test |
|------+------+------+------+------|
| 1    | 2    | 3    | 4    | 5    |
|      |      |      |      |      |


* Related Works, People, Papers, Etc

- [[http://www.the-singleton.com][My Blog @ The-Singleton]]
- [[http://www.eecs.ucf.edu/~leavens/][Gary Leaven's Research Page @ UCF]]
- [[http://www.cs.stevens.edu/~naumann/][David Naumann's Page]] 
- [[http://types.cs.washington.edu/checker-framework/][The Checker Framework]]
- [[http://docs.lib.purdue.edu/cgi/viewcontent.cgi?article=1123&context=cstech][Paper on the Lattice Model of Information Flow]]




